/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    copy: typeof import('./src/components/layout/RibbonGroupComponent copy.vue')['default']
    DockComponent: typeof import('./src/components/layout/DockComponent.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    InlineToolbarComponent: typeof import('./src/components/layout/InlineToolbarComponent.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LayerSwitcherComponent: typeof import('./src/components/map/LayerSwitcherComponent.vue')['default']
    MainLayoutComponent: typeof import('./src/components/layout/MainLayoutComponent.vue')['default']
    MainMenuComponent: typeof import('./src/components/layout/MainMenuComponent.vue')['default']
    MapComponent: typeof import('./src/components/MapComponent.vue')['default']
    MeasureComponent: typeof import('./src/components/map/MeasureComponent.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    RibbonGroupComponent: typeof import('./src/components/layout/RibbonGroupComponent.vue')['default']
    RibbonItemGroupComponent: typeof import('./src/components/layout/RibbonItemGroupComponent.vue')['default']
    RibbonToolbarComponent: typeof import('./src/components/layout/RibbonToolbarComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitButton: typeof import('primevue/splitbutton')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    ToolbarComponent: typeof import('./src/components/layout/ToolbarComponent.vue')['default']
  }
}
