/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    InlineToolbarComponent: typeof import('./src/components/InlineToolbarComponent.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MainMenuComponent: typeof import('./src/components/MainMenuComponent.vue')['default']
    MapComponent: typeof import('./src/components/MapComponent.vue')['default']
    MeasureComponent: typeof import('./src/components/MeasureComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitButton: typeof import('primevue/splitbutton')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
